In [1]:
!pip install pdfminer.six

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 46.0 MB/s eta 0:00:00


In [2]:
from pdfminer.high_level import extract_text
text = extract_text('/content/HDFC_FQA.pdf')
print(text)

Frequently Asked Questions (FAQs) –

HDFC Bank SmartWealth

What is the HDFC Bank SmartWealth all about?

HDFC Bank SmartWealth is a comprehensive investment platform for all investors with cutting edge
features and user-friendly interface.





It simplifies investing by taking the mental load off investors and serving as a one-stop-shop for
all their needs.
It  helps  users  get  investment  ready  across   various  financial  products,  including  mutual  funds,
equities, bonds, and deposits.

 Users can identify their investment profile and invest appropriately.



The HDFC Bank SmartWealth offers investment solutions curated by HDFC Bank Research.
It helps users set and track their financial milestones by providing recommendations and progress
tracking.

 HDFC   Bank   SmartWealth   allows   users   to   bring   all   their   mutual   fund   investments   onto   one

platform for a consolidated view.

 Users can access various reports pertaining to their investments.

What

# Tokenization

In [3]:
import tensorflow as tf
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [5]:
tokenizer = Tokenizer()
tokenizer.fit_on_texts([text])
tokenizer.word_index

{'the': 1,
 'to': 2,
 '\uf0b7': 3,
 'bank': 4,
 'hdfc': 5,
 'and': 6,
 'smartwealth': 7,
 'a': 8,
 'you': 9,
 'your': 10,
 'can': 11,
 'on': 12,
 'in': 13,
 'of': 14,
 'is': 15,
 'investment': 16,
 'for': 17,
 'i': 18,
 'will': 19,
 'be': 20,
 'or': 21,
 'account': 22,
 'select': 23,
 'investments': 24,
 'mutual': 25,
 'fund': 26,
 'from': 27,
 'an': 28,
 'with': 29,
 'smartjar': 30,
 'are': 31,
 'funds': 32,
 'it': 33,
 'as': 34,
 'if': 35,
 'tap': 36,
 'my': 37,
 'amount': 38,
 'sip': 39,
 'through': 40,
 'portfolio': 41,
 'how': 42,
 'invest': 43,
 'what': 44,
 'at': 45,
 'option': 46,
 'have': 47,
 'details': 48,
 'by': 49,
 'all': 50,
 'smartjars': 51,
 'family': 52,
 'that': 53,
 'scheme': 54,
 'not': 55,
 'fixed': 56,
 'investing': 57,
 'once': 58,
 'profile': 59,
 'choose': 60,
 'pan': 61,
 'number': 62,
 'steps': 63,
 'existing': 64,
 'login': 65,
 'investor': 66,
 'dashboard': 67,
 'kyc': 68,
 'enter': 69,
 'bar': 70,
 'stp': 71,
 'any': 72,
 'no': 73,
 'new': 74,
 'aadhaar':

In [7]:
print(len(tokenizer.word_index)) # Total number of unique words i.e vocabulary

1369


# Arranging the words into sequence

In [10]:
input_sequences = []
for line in text.split('\n'):
  token_list = tokenizer.texts_to_sequences([line])[0]
  for i in range(1, len(token_list)):
    input_sequences.append(token_list[:i+1])
input_sequences

[[828, 592],
 [828, 592, 446],
 [828, 592, 446, 829],
 [828, 592, 446, 829, 208],
 [5, 4],
 [5, 4, 7],
 [305, 15],
 [305, 15, 1],
 [305, 15, 1, 5],
 [305, 15, 1, 5, 4],
 [305, 15, 1, 5, 4, 7],
 [305, 15, 1, 5, 4, 7, 50],
 [305, 15, 1, 5, 4, 7, 50, 447],
 [5, 4],
 [5, 4, 7],
 [5, 4, 7, 15],
 [5, 4, 7, 15, 8],
 [5, 4, 7, 15, 8, 593],
 [5, 4, 7, 15, 8, 593, 16],
 [5, 4, 7, 15, 8, 593, 16, 306],
 [5, 4, 7, 15, 8, 593, 16, 306, 17],
 [5, 4, 7, 15, 8, 593, 16, 306, 17, 50],
 [5, 4, 7, 15, 8, 593, 16, 306, 17, 50, 122],
 [5, 4, 7, 15, 8, 593, 16, 306, 17, 50, 122, 29],
 [5, 4, 7, 15, 8, 593, 16, 306, 17, 50, 122, 29, 830],
 [5, 4, 7, 15, 8, 593, 16, 306, 17, 50, 122, 29, 830, 831],
 [307, 6],
 [307, 6, 186],
 [307, 6, 186, 362],
 [307, 6, 186, 362, 363],
 [33, 832],
 [33, 832, 57],
 [33, 832, 57, 49],
 [33, 832, 57, 49, 448],
 [33, 832, 57, 49, 448, 1],
 [33, 832, 57, 49, 448, 1, 833],
 [33, 832, 57, 49, 448, 1, 833, 594],
 [33, 832, 57, 49, 448, 1, 833, 594, 154],
 [33, 832, 57, 49, 448, 1, 

# Padding

In [12]:
print(len(input_sequences[0]))
print(len(input_sequences[230]))
print(len(input_sequences[1100]))
print(len(input_sequences[670]))


2
4
13
2


In [13]:
max_len = max([len(x) for x in input_sequences])
max_len

21

In [14]:
from tensorflow.keras.preprocessing.sequence import pad_sequences
padded_input_sequences = pad_sequences(input_sequences, maxlen=max_len, padding='pre')
padded_input_sequences


array([[  0,   0,   0, ...,   0, 828, 592],
       [  0,   0,   0, ..., 828, 592, 446],
       [  0,   0,   0, ..., 592, 446, 829],
       ...,
       [  0,   0,   0, ..., 392,   1, 687],
       [  0,   0,   0, ...,   1, 687, 567],
       [  0,   0,   0, ..., 687, 567,  16]], dtype=int32)

In [16]:
len(padded_input_sequences[0])
len(padded_input_sequences[100])
len(padded_input_sequences[1300])
len(padded_input_sequences[120])
len(padded_input_sequences[1100])

21

In [17]:
x = padded_input_sequences[:,:-1]
y = padded_input_sequences[:,-1]

In [18]:
x.shape, y.shape

((9175, 20), (9175,))

In [19]:
y

array([592, 446, 829, ..., 687, 567,  16], dtype=int32)

# Changing the y array into binary array i.e 0 and 1

In [20]:
from tensorflow.keras.utils import to_categorical
y = to_categorical(y, num_classes=1370)

In [23]:
y

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

# Building LSTM model

In [24]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense

In [26]:
from logging import logProcesses
model = Sequential()
model.add(Embedding(1370, 100, input_length= max_len-1 ))
model.add(LSTM(128))
model.add(Dense(1370, activation = 'softmax'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])
model.fit(x,y,epochs = 100)

Epoch 1/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 17s 44ms/step - accuracy: 0.0568 - loss: 6.3310
Epoch 2/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.0964 - loss: 5.5822
Epoch 3/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.1131 - loss: 5.4204
Epoch 4/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 20s 41ms/step - accuracy: 0.1597 - loss: 5.1281
Epoch 5/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 21s 41ms/step - accuracy: 0.1787 - loss: 4.8097
Epoch 6/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 19s 36ms/step - accuracy: 0.1976 - loss: 4.5844
Epoch 7/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 22s 42ms/step - accuracy: 0.2292 - loss: 4.2907
Epoch 8/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.2660 - loss: 4.0375
Epoch 9/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 20s 42ms/step - accuracy: 0.2955 - loss: 3.8072
Epoch 10/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 21s 42ms/step - accuracy: 0.3052 - loss: 3.7035
Epoch 11/100
287/287 ━━━━━━━━━━━━━━━━━━━━ 12s 42ms/step - accuracy: 0.3364 - loss: 3.4522
Epoch 12/100
287/28

# Predicting the next word

In [28]:
import time
import numpy as np
text = "What are the Key features of the HDFC Bank SmartWealth?"

for i in range(100):
  token_text = tokenizer.texts_to_sequences([text])[0]
  print(token_text)
  padded_token_text = pad_sequences([token_text], maxlen=max_len, padding='pre')
  predict_token= model.predict(padded_token_text)
  print("Predict_token: ", predict_token)
  predicted = np.argmax(predict_token)
  print("predicted: ",predicted)

  for word, index in tokenizer.word_index.items():
    # print("word:", word+" index: ", index)
    if index == predicted:
      text = text+" "+word
      print(text)
      time.sleep(2)

[44, 31, 1, 453, 307, 14, 1, 5, 4, 7]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
Predict_token:  [[5.82250781e-09 1.12476517e-02 4.33974819e-05 ... 1.22144802e-14
  1.00110135e-10 4.77543427e-09]]
predicted:  471
What are the Key features of the HDFC Bank SmartWealth? application
[44, 31, 1, 453, 307, 14, 1, 5, 4, 7, 471]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
Predict_token:  [[9.2884672e-10 1.0355707e-03 1.1321335e-06 ... 1.3085045e-14
  7.4465456e-13 8.5827628e-10]]
predicted:  12
What are the Key features of the HDFC Bank SmartWealth? application on
[44, 31, 1, 453, 307, 14, 1, 5, 4, 7, 471, 12]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step
Predict_token:  [[4.6861526e-10 7.5723648e-01 7.4664558e-07 ... 5.3135144e-16
  1.4734407e-15 4.4527151e-10]]
predicted:  1
What are the Key features of the HDFC Bank SmartWealth? application on the
[44, 31, 1, 453, 307, 14, 1, 5, 4, 7, 471, 12, 1]
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
Predict_token:  [[7.0140977e-08 7.1941485e-04 1.8129173e-03 ... 9.0945775e-